### ISSUE TITLE
class Calculator | func multiply

### ISSUE THREAD

**Issue by MohammedAlMawlawi** [MohammedAlMawlawi/INFS3203_Sec_1_Group2#3]
**Code Review**
_Read the code if syntax errors are present
Enhancement if any_

**Code Run Test**
_Run the code and check if it works_
_Check the input and processed output_

**Features Enhancement**
_Can the user experience be enhanced_

**Comment by 60088665** [comment]
Code Review
-no syntax error was found.

Code Run Test
-All the output/input process seems to be normal.

Features Enhancement
-No enhance feature can be implemented.
