### ISSUE TITLE
class Calculator | func divide

### ISSUE THREAD

**Issue by MohammedAlMawlawi** [MohammedAlMawlawi/INFS3203_Sec_1_Group2#4]
**Code Review**
_Read the code if syntax errors are present_
Enhancement if any
**Code Run Test**
_Run the code and check if it works
Check the input and processed output_
**Features Enhancement**
_Can the user experience be enhanced_

**Comment by 60088665** [comment]
Code Review
-A syntax error was found , where the operation would add numbers instead of subtracting them.

Code Run Test
-All the output/input process seems to be normal.

Features Enhancement
-No enhance feature can be implemented.
