### ISSUE TITLE
func main| func square_root | lines 33 - 40

### ISSUE THREAD

**Issue by MohammedAlMawlawi** [MohammedAlMawlawi/INFS3203_Sec_1_Group2#8]
Please note that from lines 27 to 31 are common, however, we might need to sepearate this into a function where the messages depend on type of function as some may require only one entry.

def main():
    calc = Calculator()

#the lines from 33 - 40

    if operation == "add":
        print(calc.add(x, y))
    elif operation == "subtract":
        print(calc.subtract(x, y))
    elif operation == "multiply":
        print(calc.multiply(x, y))
    elif operation == "divide":
        print(calc.divide(x, y))

**Comment by 60088665** [comment]
I Have Created a code that seemed to be more efficient in the long run
